dist: xenial

services:
  - docker

language: python

python: 3.7

before_install:
  - docker-compose -v
  - docker -v

matrix:
  include:
    - name: Cookiecutter Generation
      script: tox -e py37
    - name: Docker
      script: sh tests/test_docker.sh

install:
  - pip install tox

notifications:
  email:
    on_success: change
    on_failure: always
