# Generated by Django 2.2.5 on 2019-09-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='subscription_status',
            new_name='vendor_subscription_status',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Full Name'),
        ),
    ]
